### ISSUE TITLE
Error in conver.php

### ISSUE THREAD

**Issue by realhus** [MichaelBelgium/Youtube-to-mp3-API#1]
Hello, i have followed all the steps for API option
im getting this when i run convert.php
{ "error" : true, "type": "Exception" }

**Comment by MichaelBelgium** [comment]
What video and API are you trying?

**Comment by Darkeen** [comment]
Same here trying to make my own converter.
I've all the requirements installed

**Comment by realhus** [comment]
nevermind it worked
the problem was with composer not installed correctly
