### ISSUE TITLE
help to run on heroku

### ISSUE THREAD

**Issue by AYMENJD** [MichaelBelgium/Youtube-to-mp3-API#19]
Hi sorry for disturbing you can you make composer.lock file that we can run your project on heroku the reason we can't run your project is there is no composer.lock file and heroku failed to deploy it 
Best regards,

**Comment by MichaelBelgium** [comment]
You cant run `composer install` ?

**Comment by AYMENJD** [comment]
> You cant run `composer install` ?

No it's required composer.lock file most scripts are run there like youtube-dl + ffmpeg I don't want to use your api that mentioned on readme.md file because I will use it for my Telegram bots may if I use it may your server get problem inshort try to make account and run your project https://heroku.com and if works you can make auto deploy from your readme.md file 
Best regards,

**Comment by AYMENJD** [comment]
Can or not?
