### ISSUE TITLE
Parse error: syntax error, unexpected '.', expecting ')' in /var/www/html/search.php on line 4

### ISSUE THREAD

**Issue by EarthKiii** [MichaelBelgium/Youtube-to-mp3-API#26]
I'm stuck, i never used docker before and even with internet i'm lost ... Idk if the api var is automaticly set in search.php and if i must set it my self idk how to do (i did put my api key in the docker-compose.yml but after the creation of it does it do smth ?)

**Comment by MichaelBelgium** [comment]
Can u show me the first 10 lines of search.php on your docker?

**Comment by EarthKiii** [comment]
> Can u show me the first 10 lines of search.php on your docker?

I tried to access to it but idk how

**Comment by MichaelBelgium** [comment]
I don't use docker so it's shitty i can't reproduce or test it out, but my first thought would be [this line ](https://github.com/MichaelBelgium/Youtube-API/blob/master/Dockerfile#L15).

Did you set a google api key?

**Comment by EarthKiii** [comment]
I trought it was in docker-compose where to set my key. So i did replace the 2 API_KEY by my api key in Dockerfile but nothing changed

**Comment by EarthKiii** [comment]
So ?

**Comment by dennorske** [comment]
Sorry I haven't checked in for a while. I added the docker functionality for this.

Yes, variable is set automatically for you when you define it.
might be that there's been a change I haven't adapted for, so I will test run this and get back to you.
