### ISSUE TITLE
Installed everything needed yet it doesn't work (I'm bad at this stuff, help would be very much appreciated)

### ISSUE THREAD

**Issue by Smigg-y** [MichaelBelgium/Youtube-to-mp3-API#27]
The command "'/usr/local/bin/youtube-dl' 'https://www.youtube.com/watch?v=HPc8QMycGno' '--no-playlist' '--ignore-config' '--write-info-json' '--extract-audio' '--audio-format=mp3' '--audio-quality=0' '--output=%(id)s.%(ext)s'" failed. Exit Code: 1(General error) Working directory: download/ Output: ================ [youtube] HPc8QMycGno: Downloading webpage [youtube] Downloading just video HPc8QMycGno because of --no-playlist [youtube] HPc8QMycGno: Downloading player 38c5f870 [info] Writing video description metadata as JSON to: HPc8QMycGno.info.json Error Output: ================ WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this. WARNING: Writing cache to u'/var/www/.cache/youtube-dl/youtube-sigfuncs/js_38c5f870_109.json' failed: Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/youtube_dl/cache.py", line 49, in store os.makedirs(os.path.dirname(fn)) File "/usr/lib/python2.7/os.py", line 150, in makedirs makedirs(head, mode) File "/usr/lib/python2.7/os.py", line 150, in makedirs makedirs(head, mode) File "/usr/lib/python2.7/os.py", line 157, in makedirs mkdir(name, mode) OSError: [Errno 13] Permission denied: '/var/www/.cache' WARNING: Writing cache to u'/var/www/.cache/youtube-dl/youtube-sigfuncs/js_38c5f870_105.json' failed: Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/youtube_dl/cache.py", line 49, in store os.makedirs(os.path.dirname(fn)) File "/usr/lib/python2.7/os.py", line 150, in makedirs makedirs(head, mode) File "/usr/lib/python2.7/os.py", line 150, in makedirs makedirs(head, mode) File "/usr/lib/python2.7/os.py", line 157, in makedirs mkdir(name, mode) OSError: [Errno 13] Permission denied: '/var/www/.cache' ERROR: Cannot write metadata to JSON file HPc8QMycGno.info.json

**Comment by Smigg-y** [comment]
fixed permission issue but i now have this:

`The command "'/usr/local/bin/youtube-dl' 'https://www.youtube.com/watch?v=HPc8QMycGno' '--no-playlist' '--ignore-config' '--write-info-json' '--extract-audio' '--audio-format=mp3' '--audio-quality=0' '--output=%(id)s.%(ext)s'" failed. Exit Code: 1(General error) Working directory: download/ Output: ================ [youtube] HPc8QMycGno: Downloading webpage [youtube] Downloading just video HPc8QMycGno because of --no-playlist [youtube] HPc8QMycGno: Downloading player 38c5f870 [info] Writing video description metadata as JSON to: HPc8QMycGno.info.json Error Output: ================ WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this. ERROR: Cannot write metadata to JSON file HPc8QMycGno.info.json`

**Comment by Smigg-y** [comment]
fixed: `sudo chmod 777 download`
closing issue

**Comment by MichaelBelgium** [comment]
Yeah thats what the readme says [here](https://github.com/MichaelBelgium/Youtube-API/tree/master/download) Althought i wouldn't recommend chmod, i'd make www-data (or whatever the webserver user is) owner of the folder (with `chown`)
