### ISSUE TITLE
youtube-dl

### ISSUE THREAD

**Issue by miyakedev** [MichaelBelgium/Youtube-to-mp3-API#3]
Hi. I use this line : $dl->setBinPath(__DIR__.'/youtube-dl/youtube-dl');
so now i need use the setPythonPath but I use Linux, so i need install a Phyton Path for Linux, right?

**Comment by miyakedev** [comment]
But appears the same message

**Comment by MichaelBelgium** [comment]
I don't think it's needed to put the python path? What output do u get when u only set the bin path?
