### ISSUE TITLE
how to create own api

### ISSUE THREAD

**Issue by IsProdigy** [MichaelBelgium/Youtube-to-mp3-API#35]
Anyway I managed to use the api and I liked it a lot, could you make the tutorial more explanatory to create our own api?  thanks.

**Comment by MichaelBelgium** [comment]
You mean this: https://github.com/MichaelBelgium/Youtube-API ?

**Comment by IsProdigy** [comment]
Yes, but unfortunately I didn't understand

**Comment by MichaelBelgium** [comment]
Well it's a compact explanation and should be enough. What don't you understand?

**Comment by IsProdigy** [comment]
I didn't understand how to make my own api because I only have knowledge of the pawn language, but I already created my app on google and got my key

**Comment by IsProdigy** [comment]
I noticed that the programming language used to create the API is PHP. I will install the composer and then run the commands you left in the tutorial and see if I can advance for the next steps.

**Comment by IsProdigy** [comment]
I already downloaded yt-dlp and libmp3lame, just need to download ffmpeg.  I already edited the src/Config.php file and put the key in the docker-compose.yml file, but I am not able to execute the command " sudo docker-compose up -d " the terminal does not recognize the command, it is necessary to download something to use " sudo " commands ?

**Comment by IsProdigy** [comment]
error when executing the command " sudo docker-compose up -d " the terminal responds that " Sudowin service is stopped "

**Comment by MichaelBelgium** [comment]
Are you using docker on linux?

**Comment by IsProdigy** [comment]
Windows

**Comment by MichaelBelgium** [comment]
You don't need to use "sudo" then? sudo doesn't even exist on windows

**Comment by IsProdigy** [comment]
so after downloading the files and configuring the "src/Config.php" is the api ready to use?  how do i get it online?  youtube-dl and
 ffmpeg (+ libmp3lame) should be in the project root folder?

**Comment by MichaelBelgium** [comment]
You need a place where the project is publicly available, like a server. 
youtube-dl, ffmpeg and libmp3lame should then be installed on that server

**Comment by IsProdigy** [comment]
ok, i have a vps, what do i do after downloading youtube-dl, ffmpeg and libmp3lame and the api files?

**Comment by IsProdigy** [comment]
how do i turn on the api?  how do i use the api?  on the samp server?

**Comment by dennorske** [comment]
I Herbert!

Nice to hear you are enjoying the API :) 

If you don't know how to publicly host a webpage or set up a host for your application, it would be good to understand the basics of that, before jumping into this directly. **You need to learn to walk before you can run.**

Please consider learning/understanding the basics. You will need to know:
1. How to set up a web server
2. How to set up DNS (if you are hosting this outside of your home network, that is!)
3. How to configure this application-

The API is essentially just a "website" that can give you responses. If you host this, the API will give you the data you request from it.

Then, in SA-MP, in your scripts, you will have to consume this API using HTTP requests.

**Comment by IsProdigy** [comment]
I understand, thanks friend, I will use Michael Belgium's include to consume the api, I will study to understand how to make the api work.

**Comment by dennorske** [comment]
Good! In the mean time you can feel free to use mine.
http://yt2mp3.ducky.rocks/

It's http so it's compatible with samp native functions. I don't mind people enjoying it.

**Comment by IsProdigy** [comment]
thank you friend.

**Comment by IsProdigy** [comment]
I already had xampp on my VPS because I use mysql on my samp server, I think I installed the API correctly, the API link to do research is MichaelBelgium\YoutubeConverter ?

**Comment by IsProdigy** [comment]
![image](https://user-images.githubusercontent.com/105074040/170525524-ecec5906-2751-42da-b494-4ff4d4ba0fce.png)

Making an API work and making some music is working, but the conversion part just keeps loading and doesn't work. ffmpeg, libmp3lame and yt-dl should be in the C: directory?

**Comment by dennorske** [comment]
You need to have it installed and available in PATH yes :)

**Comment by IsProdigy** [comment]
My operating system is windows, is it still necessary to do this?

**Comment by IsProdigy** [comment]
Conversion problems, what could it be?

http://181.214.221.43/youtubebtv/

**Comment by IsProdigy** [comment]
![Screenshot_20220530-135652](https://user-images.githubusercontent.com/105074040/171035195-8cec3aa6-1b43-4d91-8258-ee01400afd4e.png)

I need help configuring the PATH for the site to be able to convert the music, that's all it takes for the site to be ready.  I use windows.

**Comment by dennorske** [comment]
@MichaelBelgium where is bin path set? Is it locked to Linux?

I can't see option to change it in src/Config.php, see his last response above.

**Comment by IsProdigy** [comment]
I use windows not linux.

**Comment by MichaelBelgium** [comment]
@dennorske it automaticly sets it to yt-dlp if it finds the executable on the system. I'm sure it should work for windows too

https://github.com/MichaelBelgium/Youtube-API/blob/909661158e5c9c8283e60f539f7a465d2a1cb105/convert.php#L36

https://github.com/MichaelBelgium/Youtube-API/blob/909661158e5c9c8283e60f539f7a465d2a1cb105/convert.php#L43-L44

If it says you don't have youtube-dl, then it couldn't find either of them (yt-dlp and youtube-dl) on the system

EDIT: unless it needs `.exe` or something for windows 🤔 

@HebertLuiiz Can you show a screenshot from the folder where you installed youtube-dl or yt-dlp

**Comment by IsProdigy** [comment]
![Screenshot_20220530-194215](https://user-images.githubusercontent.com/105074040/171065716-4fa88bf5-dbfc-44e2-8c77-fadd7df3c7b4.png)

yt-dlp, libmp3lame and ffmpeg is located in the C: directory:

**Comment by MichaelBelgium** [comment]
Open yt-dlp and ss

**Comment by IsProdigy** [comment]
yt-dlp is in the downloads folder, when I try to run yt-dlp.exe it starts and closes immediately, but I ran some commands in the terminal and managed to download a song, but on the website it still doesn't work, I have to configure it in the PATH ?

**Comment by MichaelBelgium** [comment]
Yes it needs to be in the PATH so the executable can be found from anywhere on the system

**Comment by IsProdigy** [comment]
![Screenshot_20220531-071254~2](https://user-images.githubusercontent.com/105074040/171150959-ff2aaab9-7967-42b3-a1a9-74075ff77d97.png)
![Screenshot_20220531-071024~2](https://user-images.githubusercontent.com/105074040/171150979-0215221e-fc27-47c5-9c7b-8b59fb536ab9.png)
![Screenshot_20220531-071422~2](https://user-images.githubusercontent.com/105074040/171151000-95a76c94-f8ba-4deb-ad9b-9da228e02f33.png)

everything seems to be ok right?

**Comment by MichaelBelgium** [comment]
Yes

**Comment by HebertLuiiz** [comment]
![Uploading Screenshot_20220531-075703~2.png…]()

I don't understand why this is still happening.

**Comment by IsProdigy** [comment]
![Screenshot_20220531-075703~2](https://user-images.githubusercontent.com/105074040/171158876-bf476032-b8e1-4629-8cce-ae7486e59d18.png)

I don't understand why this is still happening.
Is the PATH to be configured for the user or for the system?

**Comment by IsProdigy** [comment]
should i download python on my windows?

**Comment by MichaelBelgium** [comment]
There's one thing left to do and thats editing  this line

https://github.com/MichaelBelgium/Youtube-API/blob/909661158e5c9c8283e60f539f7a465d2a1cb105/convert.php#L36

Changed `'yt-dlp'` to `'yt-dlp.exe'`

And see if that fixes it

**Comment by IsProdigy** [comment]
Ok

**Comment by IsProdigy** [comment]
unfortunately it didn't work :( apparently this error only occurs on Windows.

**Comment by IsProdigy** [comment]
yt-dlp must be in a specific folder in the C: directory?

**Comment by IsProdigy** [comment]
solved, thanks a lot for the help.

**Comment by MichaelBelgium** [comment]
How did you solve it?

**Comment by IsProdigy** [comment]
The PATH setting was only accepted after restarting the VPS.
