### ISSUE TITLE
quota limit

### ISSUE THREAD

**Issue by IsProdigy** [MichaelBelgium/Youtube-to-mp3-API#37]
Hi, is there any way to bypass the YouTube API quota limit?  there is a search limit, after exceeding the limit the API is blocked and is only unlocked the next day.  is there a way to solve this or just looking for another API?  Will the spotify API solve my problem?

**Comment by MichaelBelgium** [comment]
No, there's no way to bypass it. Its origin is from Youtube itself so ..

**Comment by IsProdigy** [comment]
So the solution is to resort to another API ? How the spotify API for example, could bring a laravel of it to us?

**Comment by dennorske** [comment]
Youtube and spotify both have quota limits and rate limiting on their API's. [Youtube (click) ](https://developers.google.com/youtube/v3/getting-started#quota ) has 10.000 API calls per day. [Here ](https://developers.google.com/youtube/v3/getting-started#calculating-quota-usage)is what each action costs.
You can however [ask to upgrade the quota here by filling this form.](https://support.google.com/youtube/contact/yt_api_form) 

Spotify has the same setup - you can read more here: https://developer.spotify.com/documentation/web-api/guides/rate-limits/
(Development vs. production mode).

**Comment by IsProdigy** [comment]
I filled out the form, just wait for the answer. Thanks.

**Comment by dennorske** [comment]
Feel free to close this issue if there's nothing else, as this is slightly unrelated to the project itself :) 

Good luck!

**Comment by IsProdigy** [comment]
YouTube didn't approve my extended quota request, so I don't think I will be able to use the API to serve my purposes, I will analyze the spotify API I believe that this API will not exceed the quota limit just for searching some songs.  thanks for listening.
