### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by pungpond78** [MichaelBelgium/Youtube-to-mp3-API#40]
<br />
<b>Fatal error</b>:  Uncaught Error: Class &quot;MichaelBelgium\YoutubeConverter\Config&quot; not found in C:\xampp\htdocs\convert.php:34
Stack trace:
#0 {main}
  thrown in <b>C:\xampp\htdocs\convert.php</b> on line <b>34</b><br />

**Comment by MichaelBelgium** [comment]
Did you edit anything? That error shouldn't be possible because of 

https://github.com/MichaelBelgium/Youtube-API/blob/abbf853bf0062af76429efe5d394e434b387bbb3/convert.php#L4

**Comment by pungpond78** [comment]
I downloaded the original file and installed it on the web server but still error (and I haven't edited the file.)



**Warning: require_once(C:\xampp\htdocs\youtube_stream/vendor/autoload.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\youtube_stream\convert.php on line 2

Fatal error: Uncaught Error: Failed opening required 'C:\xampp\htdocs\youtube_stream/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\youtube_stream\convert.php:2 Stack trace: #0 {main} thrown in C:\xampp\htdocs\youtube_stream\convert.php on line 2**
