### ISSUE TITLE
Options section to be added

### ISSUE THREAD

**Issue by BCC-BGChatCommunity** [MichaelBelgium/Youtube-to-mp3-API#42]
Can i add some other options in the start convert yt-dlp. I mean exactly --no-mtime . Becouse i want date and time of the saved file to be real date when convert is made not youtube changes.
Tnx

**Comment by MichaelBelgium** [comment]
Yes you can add more options. For the `--no-mtime` option there's the `noMtime`  option in the Options class

https://github.com/norkunas/youtube-dl-php/blob/1bd8a63a27a4bc139a42502947ad9e68c46d907a/src/Options.php#L874
