### ISSUE TITLE
this issue

### ISSUE THREAD

**Issue by qwertyuiop5t** [MichaelBelgium/Youtube-to-mp3-API#44]
"<br />\n<b>Warning</b>:  require_once(D:\\XAMPP\\htdocs\\new\\Youtube-API-master\\vendor/composer/autoload_real.php): failed to open stream: No such file or directory in <b>D:\\XAMPP\\htdocs\\new\\Youtube-API-master\\vendor\\autoload.php</b> on line <b>23</b><br />\n<br />\n<b>Fatal error</b>:  require_once(): Failed opening required 'D:\\XAMPP\\htdocs\\new\\Youtube-API-master\\vendor/composer/autoload_real.php' (include_path='D:\\XAMPP\\php\\PEAR') in <b>D:\\XAMPP\\htdocs\\new\\Youtube-API-master\\vendor\\autoload.php</b> on line <b>23</b><br />\n"

**Comment by MichaelBelgium** [comment]
Install composer packages

`composer install`
