### ISSUE TITLE
Conversion videos with special characters

### ISSUE THREAD

**Issue by marcelog09** [MichaelBelgium/Youtube-to-mp3-API#47]
I can't convert videos that have special characters in their title, for example (https://www.youtube.com/watch?v=eD2F5wuxqoQ):

[28-May-2023 03:36:00 Europe/Berlin] PHP Warning:  file_get_contents(download\6. Major RD feat Azzy - 60K REMIX  (prod. @baratafather)-eD2F5wuxqoQ.info.json): Failed to open stream: No such file or directory in C:\xampp\htdocs\convert\vendor\norkunas\youtube-dl-php\src\Metadata\DefaultMetadataReader.php on line 16

Is there any solution?

**Comment by dennorske** [comment]
I am able to reproduce the issue, and I think this could be due to the API is not sanitizing the file name before writing it. That should be an easy fix

**Comment by MichaelBelgium** [comment]
I tried converting that video on youtube.michaelbelgium.me and it does work

```
{
    "error": false,
    "youtube_id": "eD2F5wuxqoQ",
    "title": "6. Major RD feat Azzy - 60K REMIX 🏆 (prod. @baratafather)",
    "alt_title": null,
    "duration": 174,
    "file": "https://youtube.michaelbelgium.me/storage/eD2F5wuxqoQ.mp3",
    "uploaded_at": {
        "date": "2021-09-27 15:43:12.000000",
        "timezone_type": 3,
        "timezone": "Europe/Brussels"
    }
}
```

But youtube.michaelbelgium.me is using this repo https://github.com/MichaelBelgium/Laravel-Youtube-API
Althou it's based on this repo ... 

I'm gonna try it without the laravel instance

EDIT: It looks like you changed this line so it included the video title too right?

https://github.com/MichaelBelgium/Youtube-API/blob/698e772ea979af48abfba9d79c35547a5eab0ae8/convert.php#L68

**Comment by marcelog09** [comment]
> I tried converting that video on youtube.michaelbelgium.me and it does work
> 
> ```
> {
>     "error": false,
>     "youtube_id": "eD2F5wuxqoQ",
>     "title": "6. Major RD feat Azzy - 60K REMIX 🏆 (prod. @baratafather)",
>     "alt_title": null,
>     "duration": 174,
>     "file": "https://youtube.michaelbelgium.me/storage/eD2F5wuxqoQ.mp3",
>     "uploaded_at": {
>         "date": "2021-09-27 15:43:12.000000",
>         "timezone_type": 3,
>         "timezone": "Europe/Brussels"
>     }
> }
> ```
> 
> But youtube.michaelbelgium.me is using this repo https://github.com/MichaelBelgium/Laravel-Youtube-API Althou it's based on this repo ...
> 
> I'm gonna try it without the laravel instance
> 
> EDIT: It looks like you changed this line so it included the video title too right?
> 
> https://github.com/MichaelBelgium/Youtube-API/blob/698e772ea979af48abfba9d79c35547a5eab0ae8/convert.php#L68

Hi, i didn't make any changes to the files

```
    if(!$exists)
    {
        $options = Options::create()
            // ->ffmpegLocation('/usr/local/bin/ffmpeg')
            ->output('%(id)s.%(ext)s')
            ->downloadPath(Config::DOWNLOAD_FOLDER)
            ->noPlaylist()
            ->url($youtubelink);

        if($format == 'mp3')
        {
            $options = $options->extractAudio(true)
                ->audioFormat('mp3')
                ->audioQuality('0');
        }
        else
            $options = $options->format('bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best');
    }
```

**Comment by MichaelBelgium** [comment]
That's odd because the PHP warning says `download\6. Major RD feat Azzy - 60K REMIX (prod. @baratafather)-eD2F5wuxqoQ.info.json` while the output is set only to `id`

When I try it, it writes to `download/eD2F5wuxqoQ.info.json`

Can you check via command line to see what it does:

```
yt-dlp --ignore-config --ignore-errors --write-info-json --no-playlist --output="download/%(id)s.%(ext)s" --extract-audio --audio-format=mp3 --audio-quality=0 https://www.youtube.com/watch?v=eD2F5wuxqoQ
```

(or if you use youtube-dl , change `yt-dlp` to `youtube-dl`)

**Comment by marcelog09** [comment]
Really, per CMD everything happens normally:

`yt-dlp --ignore-config --ignore-errors --write-info-json --no-playlist --output="download/%(id)s.%(ext)s" --extract-audio --audio-format=mp3 --audio-quality=0 https://www.youtube.com/watch?v=eD2F5wuxqoQ `

```
yt-dlp --ignore-config --ignore-errors --write-info-json --no-playlist --output="download/%(id)s.%(ext)s" --extract-audio --audio-format=mp3 --audio-quality=0 https://www.youtube.com/watch?v=eD2F5wuxqoQ
[youtube] Extracting URL: https://www.youtube.com/watch?v=eD2F5wuxqoQ
[youtube] eD2F5wuxqoQ: Downloading webpage
[youtube] eD2F5wuxqoQ: Downloading android player API JSON
[info] eD2F5wuxqoQ: Downloading 1 format(s): 251
[info] Writing video metadata as JSON to: download\eD2F5wuxqoQ.info.json
[dashsegments] Total fragments: 1
[download] Destination: download\eD2F5wuxqoQ.webm
[download] 100% of    2.83MiB in 00:00:00 at 24.18MiB/s
[ExtractAudio] Destination: download\eD2F5wuxqoQ.mp3
Deleting original file download\eD2F5wuxqoQ.webm (pass -k to keep)
```

![mp3](https://github.com/MichaelBelgium/Youtube-API/assets/55034630/90d74c6c-3324-4f74-ae88-5ff89883019e)
> 

I noticed that this started to happen when I migrated from Linux to Windows. Could it be related or something?

**Comment by MichaelBelgium** [comment]
Hmm no idea, does it actually happen every time? Even with other videos?

**Comment by marcelog09** [comment]
I downloaded the most up-to-date version from the repository and it started working normally.

**Comment by marcelog09** [comment]
> Hmm no idea, does it actually happen every time? Even with other videos?

This is the strangest thing, it only happens with some specific videos, while others don't. I recorded a video about:

https://www.youtube.com/watch?v=DGX09LpDFi4

EDIT:

I think I found a pattern:

1. If the video has already been converted before, and the .MP3 file is still in the folder, the problem occurs.
2. It only happens with some specific videos (I believe those with titles with special characters)

**Comment by MichaelBelgium** [comment]
> If the video has already been converted before, and the .MP3 file is still in the folder, the problem occurs.

That won't happen, if it already exists, it'll re-use the file and downloading get skipped, which means there won't be any json file

Is everything updated? All the packages in composer.json? You could try executing `composer update`
