### ISSUE TITLE
Cannot write metadata to JSON file

### ISSUE THREAD

**Issue by ghost** [MichaelBelgium/Youtube-to-mp3-API#6]
Hello I am trying to host this myself and have come up with an error trying to convert videos.

> The command "'/usr/local/bin/youtube-dl' 'https://youtube.com/watch?v=6TWJaFD6R2s' '--no-playlist' '--ignore-config' '--write-info-json' '--extract-audio' '--audio-format=mp3' '--audio-quality=0' '--output=%(id)s.%(ext)s'" failed.
> 
> Exit Code: 1(General error)
> 
> Working directory: /var/www/html/ytconverter/download/
> 
> Output:
> ================
> [youtube] 6TWJaFD6R2s: Downloading webpage
> [youtube] 6TWJaFD6R2s: Downloading video info webpage
> [youtube] Downloading just video 6TWJaFD6R2s because of --no-playlist
> [info] Writing video description metadata as JSON to: 6TWJaFD6R2s.info.json
> 
> 
> Error Output:
> ================
> WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
> ERROR: Cannot write metadata to JSON file 6TWJaFD6R2s.info.json

**Comment by MichaelBelgium** [comment]
* Is the download folder writable for the webserver? (I assume yes anyway)
* Are you using the latest youtube-dl version? (`youtube-dl -U`)

**Comment by ghost** [comment]
> * Is the download folder writable for the webserver? (I assume yes anyway)
> * Are you using the latest youtube-dl version? (`youtube-dl -U`)

Yeah it is up to date and the download folder is definitely writable.

**Comment by MichaelBelgium** [comment]
Is it with every video or only that one? You could try to set the LC_ALL env variable

**Comment by ghost** [comment]
> Is it with every video or only that one? You could try to set the LC_ALL env variable

I set the LC_ALL variable and it happens with any video I regardless of whether I use search or just request a specific video

**Comment by MichaelBelgium** [comment]
Is it possible the json file already exists? I've searched around and although that can be a reason on windows systems, yet i see you're using linux so I'm not sure about it. Can't really come up with a solution, you could try to make an issue in [the youtube-dl-php repo](https://github.com/norkunas/youtube-dl-php)

**Comment by mrhussnain** [comment]
i am facing same issue please help thanks

**Comment by MichaelBelgium** [comment]
@mrhussnain exactly the same error? Show me the full error message
