### ISSUE TITLE
Unsupported declare 'strict_types'

### ISSUE THREAD

**Issue by winbotscript** [MichaelBelgium/Youtube-to-mp3-API#7]
I got an error

<br />
<b>Warning</b>:  Unsupported declare 'strict_types' in <b>/home/admin/domain/api/ytconvertmp3/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php</b> on line <b>3</b><br />
<br />
<b>Parse error</b>:  syntax error, unexpected ':', expecting ';' or '{' in <b>/home/admin/domain/api/ytconvertmp3/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php</b> on line <b>112</b><br />

Help me please

**Comment by MichaelBelgium** [comment]
You probably have not the required php version. Which version do you use?

**Comment by winbotscript** [comment]
I use PHP 7, can u telp me to resolve this issue ?

**Comment by MichaelBelgium** [comment]
You need php version > 7.0.8 although composer should've checked on that when installing?

**Comment by winbotscript** [comment]
I have already install PHP 7.0.8 but still same an error

**Comment by winbotscript** [comment]
Exactly i am use multiple PHP, can you help me for resolve this problem ?

https://prnt.sc/o65fi7

**Comment by MichaelBelgium** [comment]
Change the first selected php version to php71

**Comment by winbotscript** [comment]
Now i get issue like this:

{"error":true,"message":"\"youtube-dl\" executable was not found. Did you forgot to add it to environment variables? Or set it via $yt->setBinPath('\/usr\/bin\/youtube-dl')."}

help me please

**Comment by winbotscript** [comment]
Which youtube-dl

/opt/rh/rh-python36/root/usr/bin/youtube-dl

How to resolve this issue ???

**Comment by MichaelBelgium** [comment]
If you installed youtube-dl and it can't find it you can add it to your PATH env variable.  Or like the error said use `setBinPath()` and that path you wrote above as parameter

**Comment by winbotscript** [comment]
Please give me an example and which file i must to change ? cause i am newbie

**Comment by MichaelBelgium** [comment]
Under [line 42](https://github.com/MichaelBelgium/Youtube-to-mp3-API/blob/master/convert.php#L42) you can write 
```PHP
$dl->setBinPath('/opt/rh/rh-python36/root/usr/bin/youtube-dl');
```

**Comment by winbotscript** [comment]
Thanks for your help, but i get an issue again {"error":true,"message":"The Process class relies on proc_open, which is not available on your PHP installation."}

My PHP 7.1.30 (cli)

Help me please
