### ISSUE TITLE
Accept youtu.be share links

### ISSUE THREAD

**Issue by MichaelBelgium** [MichaelBelgium/Youtube-to-mp3-API#9]
Add possibility to paste `youtu.be/video-id` urls in `youtubelink` GET parameter

**Comment by alisahanyalcin** [comment]
**you can review here;**
https://github.com/alisahanyalcin/Youtube-to-mp3-API/blob/patch-1/convert.php

**Comment by MichaelBelgium** [comment]
@alisahanyalcin please make a PR of that
